### ISSUE TITLE
Empty documentation pages with `latest`

### ISSUE THREAD

**Issue by Ngoguey42** [Ngoguey42/buzzard#19]
Most pages of the latest documentation are empty: https://buzzard.readthedocs.io/en/latest/footprint.html

This works fine with the stable one: https://buzzard.readthedocs.io/en/stable/footprint.html

**Comment by ashnair1** [comment]
Seems autodoc can't find `gdal` in path.

**Comment by ashnair1** [comment]
Fixed by #24
